# Generated by Django 3.2.7 on 2021-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('step', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('familiyasi', models.CharField(blank=True, max_length=128, null=True)),
                ('ismi', models.CharField(blank=True, max_length=128, null=True)),
                ('otasini_ismi', models.CharField(blank=True, max_length=128, null=True)),
                ('tugulgan_sana', models.CharField(blank=True, max_length=128, null=True)),
                ('malumoti', models.CharField(blank=True, max_length=64, null=True)),
                ('talim_olgan', models.CharField(blank=True, max_length=1024, null=True)),
                ('oilaviy', models.CharField(blank=True, max_length=64, null=True)),
                ('mutaxasis', models.CharField(blank=True, max_length=128, null=True)),
                ('manzil_vil', models.CharField(blank=True, max_length=128, null=True)),
                ('manzil_tum', models.CharField(blank=True, max_length=128, null=True)),
                ('manzil', models.CharField(blank=True, max_length=1024, null=True)),
                ('ish_joyi', models.CharField(blank=True, max_length=512, null=True)),
                ('lavozimi', models.CharField(blank=True, max_length=512, null=True)),
                ('tel_raq', models.CharField(blank=True, max_length=512, null=True)),
                ('tel_raq_qosh', models.CharField(blank=True, max_length=512, null=True)),
                ('qay_til', models.CharField(blank=True, max_length=512, null=True)),
                ('ish_davri', models.CharField(blank=True, max_length=1024, null=True)),
                ('qay_das', models.CharField(blank=True, max_length=512, null=True)),
                ('qosh_mal', models.CharField(blank=True, max_length=1024, null=True)),
                ('maosh', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
