# Generated by Django 3.2.7 on 2021-10-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
